### ISSUE TITLE
我抑郁了🌝

### ISSUE THREAD

**Issue by bukaixyz** [xiaoleGun/android_device_xiaomi_wayne-4.19#1]

**Comment by xiaoleGun** [comment]
？怎么了

**Comment by xiaoleGun** [comment]
如果没什么事我就close了

**Comment by bukaixyz** [comment]
> ？怎么了

原因有点复杂

**Comment by bukaixyz** [comment]
广西农民去年荒废我的旅游,今年暑假想旅也不行 因为有新冠了,还把我iPad砸掉了,红米也藏起来了🌝 今天暑假即将结束,作业一大堆还没做好,广西农民又多管闲事,所以我就抑郁了

**Comment by bukaixyz** [comment]
我之前在酷安上看到广西闲鱼骗子的图文,就评论广西不好,我的酷安账号就被封了🌝 🌝 🌝
