### ISSUE TITLE
device/xiaomi/wayne/light/Lights.h:20:10: fatal error: 'aidl/android/hardware/light/BnLights.h' file not found #include <aidl/android/hardware/light/BnLights.h>

### ISSUE THREAD

**Issue by kavencat** [xiaoleGun/android_device_xiaomi_wayne-4.19#5]
device/xiaomi/wayne/light/Lights.h:20:10: fatal error: 'aidl/android/hardware/light/BnLights.h' file not found
#include <aidl/android/hardware/light/BnLights.h>

**Comment by xiaoleGun** [comment]
now is done

**Comment by davigamer987** [comment]
> now is done

How did you fix?
